In [ ]:
!pip install numpy
!pip install matplotlib

  Using cached matplotlib-3.10.9-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (52 kB)
  Using cached contourpy-1.3.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.63.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (118 kB)
  Using cached kiwisolver-1.5.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
  Using cached pillow-12.2.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Using cached matplotlib-3.10.9-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.9 MB)
Using cached contourpy-1.3.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (363 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.63.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_

In [ ]:
import numpy as np

data = np.load("../96x96_tem_downsampled.npy")

print(data.shape)
print(data.columns)

(17266, 96, 96, 1)
[[[[0.6427596 ]
   [0.6418083 ]
   [0.64095   ]
   ...
   [0.6358392 ]
   [0.63776124]
   [0.6511407 ]]

  [[0.6383435 ]
   [0.63625103]
   [0.63554966]
   ...
   [0.6358052 ]
   [0.6349074 ]
   [0.64277834]]

  [[0.63676846]
   [0.6491845 ]
   [0.6435565 ]
   ...
   [0.6268854 ]
   [0.6426406 ]
   [0.6421094 ]]

  ...

  [[0.6324514 ]
   [0.6376643 ]
   [0.63518274]
   ...
   [0.62312067]
   [0.6179324 ]
   [0.6291857 ]]

  [[0.63401234]
   [0.6452    ]
   [0.643867  ]
   ...
   [0.6216642 ]
   [0.62523836]
   [0.6255861 ]]

  [[0.64044595]
   [0.6506671 ]
   [0.64996916]
   ...
   [0.62289846]
   [0.62635434]
   [0.6289858 ]]]


 [[[0.42832452]
   [0.4159846 ]
   [0.4125151 ]
   ...
   [0.46219102]
   [0.4798636 ]
   [0.47980586]]

  [[0.422575  ]
   [0.42177203]
   [0.42400444]
   ...
   [0.47090325]
   [0.48420885]
   [0.48809642]]

  [[0.42592192]
   [0.42605412]
   [0.4275782 ]
   ...
   [0.46688676]
   [0.48567218]
   [0.48106122]]

  ...

  [[0.4311901 ]
   [

In [ ]:
import matplotlib as plt

